name: auto-approve
on: pull_request

permissions:
  pull-requests: write
          
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'Njoguu' }}
    steps:
    
    - name: Approve Pull Request
      uses: juliangruber/approve-pull-request-action@v1
      with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
    - name: Merge Pull Request
      uses: juliangruber/merge-pull-request-action@v1
      with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          method: squash
        

