name: auto-approve
on: pull_request

permissions:
  pull-requests: write
          
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'Njoguu' }}
    steps:
    
    - name: Find Pull Request
      uses: juliangruber/find-pull-request-action@v1
      id: find-pull-request
      with:
        branch: main
    - run: echo "Pull Request ${number}"
      env:
        number: ${{ steps.find-pull-request.outputs.number }}
    
    - name: Approve Pull Request
      uses: juliangruber/approve-pull-request-action@v2.0.0
      with:
          github-token: ${{ secrets.GH_TOKEN }}
          number: ${{ github.event.inputs.pullRequestNumber }}
          
    - name: Merge Pull Request
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        number: ${{ github.event.inputs.pullRequestNumber }}
        method: squash # merge rebase
        repo: Njoguu/jikAPI
        

