name: Tests

on : [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PGPORT }}
      DATABASE_NAME: ${{ secrets.PGDATABASE }}
      USER: ${{ secrets.PGUSER }}
      PASSWORD: ${{ secrets.PGPASSWORD }}
      HOST: ${{ secrets.PGHOST }} 
      MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
      MAILCHIMP_REGION: ${{ secrets.MAILCHIMP_REGION }} 
      MAILCHIMP_MARKETING_AUDIENCE_ID: ${{ secrets.MAILCHIMP_MARKETING_AUDIENCE_ID }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      RECAPTCHA_API_SECRET_KEY: ${{ secrets.RECAPTCHA_API_SECRET_KEY }}
      RECAPTCHA_API_KEY: ${{ secrets.RECAPTCHA_API_KEY }}
      JWT_SECRET_KEY: ${{ secrets.RECAPTCHA_API_KEY }}
      TABLENAME: ${{ secrets.TABLENAME }}
      userTableName: ${{ secrets.USERTABLENAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run tests
        run: |
          pytest tests/
